### GET /tracks
GET http://localhost:8080/tracks HTTP/1.1

### POST /auth/register
POST http://localhost:8080/auth/signup HTTP/1.1
Content-Type: application/json

{
  	"email": "john@gmaila.com",
  	"password": "John123!",
  	"confirm_password": "John123!"
}

### POST /auth/login
POST http://localhost:8080/auth/signin HTTP/1.1
Content-Type: application/json

{
  	"email": "john@gmaila.com",
  	"password": "John123!"
}

### POST /tracks
POST http://localhost:8080/tracks HTTP/1.1
Content-Type: application/json

{
  	"date": "2024-08-15T18:30:00.000Z",
	"reps": 10,
	"exerciseId": "b9a3a9a4-6b9b-4b58-80a3-1ef84ee41af1"
}
