GET http://localhost:8080/auth HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyODdmNGFlMy1iMjc2LTQ1NjEtOTUyNS0yN2VhOGYzOTQzNTAiLCJ1c2VybmFtZSI6ImpvaG5AZ21haWxhLmNvbSIsImlhdCI6MTcyMjUxMjYyMCwiZXhwIjoxNzIyNTEzNTIwfQ.LLT652r2yOqtNjNuXFKybnRNxkji1KdDCDuxtMqWPOc
Content-Type: application/json

### POST /auth/register
POST http://localhost:8080/auth/signup HTTP/1.1
Content-Type: application/json

{
  	"email": "john@gmaila.com",
  	"password": "John123!",
  	"confirm_password": "John123!"
}

### POST /auth/login
POST http://localhost:8080/auth/signin HTTP/1.1
Content-Type: application/json

{
  	"email": "john@gmaila.com",
  	"password": "John123!"
}
